"""Generate listing images. Run with Python + Pillow after adding archive images."""
import json
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "assets" / "thumbnails"
OUTPUT.mkdir(exist_ok=True)
manifest = {}

for source in sorted((ROOT / "assets" / "archive").glob("*.png")):
    with Image.open(source) as original:
        thumbnail = original.convert("RGB")
        thumbnail.thumbnail((640, 960), Image.Resampling.LANCZOS)
        target = OUTPUT / f"{source.stem}.webp"
        thumbnail.save(target, "WEBP", quality=82, method=6)
        manifest[source.relative_to(ROOT).as_posix()] = target.relative_to(ROOT).as_posix()

with Image.open(ROOT / "assets" / "hero.png") as original:
    original.convert("RGB").save(ROOT / "assets" / "hero.webp", "WEBP", quality=85, method=6)

(ROOT / "js" / "archive-thumbnails.js").write_text(
    "// Generated by scripts/generate-thumbnails.py; missing entries use the original image.\n"
    + "window.IDK_THUMBNAILS = " + json.dumps(manifest, indent=2) + ";\n",
    encoding="utf-8",
)
